version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8001:8001

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8000:8000
